resolver: lts-13.1
flags:
  haskeline:
    brick: true
extra-package-dbs: []
packages:
- '.'
- ../PLGrammar
- ../PLParser
- ../PLPrinter
- ../PLLabel
- ../Reversible
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true
- location:
    git: https://github.com/rootmos/haskeline.git
    commit: bcd94f5cc0c4e919cbda3bb43dde482cac56dd51
  extra-dep: true
extra-deps:
- megaparsec-6.4.0
- parser-combinators-0.4.0
allow-newer: true
