flags:
  haskeline:
    brick: true
extra-package-dbs: []
packages:
- '.'
- ../PLGrammar
- ../PLParser
- ../PLPrinter
- location:
    git: https://github.com/rootmos/haskeline.git
    commit: bcd94f5cc0c4e919cbda3bb43dde482cac56dd51
  extra-dep: true
extra-deps:
- haskeline-0.7.4.0
- megaparsec-6.4.0
- parser-combinators-0.4.0
resolver: lts-9.18
